### ISSUE TITLE
Doesn't track with Divi theme

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give-Google-Analytics#12]
Here's how I tested this and confirmed that it works as expected with Twenty Seventeen, but NOT with Divi.

Installed the GA Debugger Chrome Extension:
https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en

Setup a local environment (bizconnectworld.dev) with only Twenty Seventeen, Give, Give-GA, Monster Analytics. Did a test donation from a single Give form (not a shortcode), confirmed that it tracked as intended. I can see the event sent to GA with the Chrome Debugger.

![image](https://user-images.githubusercontent.com/930724/26856957-0081c8b4-4adc-11e7-9223-d21cb92e76db.png)

Switched to Divi and did the same, and with the Chrome Debugger you can see that the "price" is reflected as "undefined":

![image](https://user-images.githubusercontent.com/930724/26856819-150cb600-4adb-11e7-877c-a6c22ac9b5c8.png)
![image](https://user-images.githubusercontent.com/930724/26856824-1c771bba-4adb-11e7-91a3-34c68fb3fd5e.png)

When I look at that code, it seems to be looking for the value of the `.give-amount-hidden` input.
https://github.com/WordImpress/Give-Google-Analytics/blob/master/includes/give-google-analytics-functions.php#L84

If I change that to `#give-amount` (the ID of the actual amount field) then I do see it defined with the GA Debugger correctly, but it's still not tracking in GA succesfully:
![image](https://user-images.githubusercontent.com/930724/26856880-896e3f1e-4adb-11e7-80a1-affb76556c44.png)

**Comment by DevinWalker** [comment]
Because we are using the GA "Measurement Protocol" to track successful donations now when a payments status changes this should be resolved: https://github.com/WordImpress/Give-Google-Analytics/blob/master/includes/give-google-analytics-functions.php#L432 

This is because the tracking code now fires server-side when a payment status is updated rather than relying on JS on the client-side to fire. 

Please note: now that we are using the "Measurement Protocol" the GA debugger tool above will not work since it's reliant on the client method.
