### ISSUE TITLE
Need to handle ec.js in addition to ecommerce.js

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give-Google-Analytics#5]
There are two ecommerce plugins for GA:

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce

and

https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce

we either need to explicitly tell users which one to use, or account for either option somewhere in a setting. 

Additionally, we need to explore how various WP Google Analytics plugins have ecommerce options set up in order to properly account for the varying options.

**Comment by DevinWalker** [comment]
For version 1.0 I've opted to use the "Enhanced Ecommerce" option. This is because I'm guessing that Google will soon deprecate the less-Enhanced version in the future.

If we release and it turns out many of our users are on the older version of analytics and can't use it or are consistently requested the older version then we can look into implementing it.
